#!/bin/bash
#PBS -N IAV
#PBS -l nodes=1:ppn=64
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID

module load hyphy

FELOPT=6
SLACOPT=1
MEMEOPT=11
ALPHA=0.1

DTYPE=$1 # TRUNK or SHALLOW

DAT=/home/sjspielman/Dropbox/Science/Manuscripts/Current/book-chapter/h3n2_ha/austin/${DTYPE}.dat
OUTPATH=/home/sjspielman/Dropbox/Science/Manuscripts/Current/book-chapter/h3n2_ha/austin/output
mkdir -p $OUTPATH
NUCFIT=$DAT.nucfit
FELOUTPUT=$DAT.fel
MEMEOUTPUT=$DAT.meme
SLACOUTPUT=$DAT.slac

####### SLAC #######
#(echo 1; echo 1; echo $DAT; echo 2; echo "012345"; echo "Y"; echo $NUCFIT; echo 5; echo $SLACOPT; echo 1; echo 1; echo 1; echo $ALPHA; echo 2; echo $SLACOUTPUT; echo 1) | HYPHYMP /opt/hyphy/hyphy-2.2.7/res/TemplateBatchFiles/QuickSelectionDetection.bf

###### FEL ########
#(echo 1; echo 2; echo $NUCFIT; echo 5; echo $FELOPT; echo $ALPHA; echo 1; echo $FELOUTPUT) | HYPHYMP /opt/hyphy/hyphy-2.2.7/res/TemplateBatchFiles/QuickSelectionDetection.bf

##### MEME #######
(echo 1; echo 2; echo $NUCFIT; echo 5; echo $MEMEOPT; echo $ALPHA; echo "N"; echo $MEMEOUTPUT) | /opt/hyphy/hyphy-2.2.7/HYPHYMP /opt/hyphy/hyphy-2.2.7/res/TemplateBatchFiles/QuickSelectionDetection.bf





